In [1]:
import numpy as np
import pandas as pd

In [2]:
house=pd.read_csv("D:\lab\ML\housepred1.csv")

In [3]:
house

,Id,Street,YearBuilt,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,GarageType,GarageCars,GarageArea,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,YrSold,SaleType,SaleCondition,SalePrice
0,1,Pave,2003,3,1,Gd,8,Typ,0,Attchd,2,548,Y,0,61,0,2008,WD,Normal,208500
1,2,Pave,1976,3,1,TA,6,Typ,1,Attchd,2,460,Y,298,0,0,2007,WD,Normal,181500
2,3,Pave,2001,3,1,Gd,6,Typ,1,Attchd,2,608,Y,0,42,0,2008,WD,Normal,223500
3,4,Pave,1915,3,1,Gd,7,Typ,1,Detchd,3,642,Y,0,35,272,2006,WD,Abnorml,140000
4,5,Pave,2000,4,1,Gd,9,Typ,1,Attchd,3,836,Y,192,84,0,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,Pave,1999,3,1,TA,7,Typ,1,Attchd,2,460,Y,0,40,0,2007,WD,Normal,175000
1456,1457,Pave,1978,3,1,TA,7,Min1,2,Attchd,2,500,Y,349,0,0,2010,WD,Normal,210000
1457,1458,Pave,1941,4,1,Gd,9,Typ,2,Attchd,1,252,Y,0,60,0,2010,WD,Normal,266500
1458,1459,Pave,1950,2,1,Gd,5,Typ,0,Attchd,1,240,Y,366,0,112,2010,WD,Normal,142125
1459,1460,Pave,1965,3,1,TA,6,Typ,0,Attchd,1,276,Y,736,68,0,2008,WD,Normal,147500

In [4]:
from sklearn.preprocessing import LabelEncoder
lr=LabelEncoder()

In [5]:
house["Street"]=lr.fit_transform(house["Street"])
house["KitchenQual"]=lr.fit_transform(house["KitchenQual"])
house["Functional"]=lr.fit_transform(house["Functional"])
house["SaleCondition"]=lr.fit_transform(house["SaleCondition"])
house["PavedDrive"]=lr.fit_transform(house["PavedDrive"])
house["SaleType"]=lr.fit_transform(house["SaleType"])
house.head()

,Id,Street,YearBuilt,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,GarageType,GarageCars,GarageArea,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,YrSold,SaleType,SaleCondition,SalePrice
0,1,1,2003,3,1,2,8,6,0,Attchd,2,548,2,0,61,0,2008,8,4,208500
1,2,1,1976,3,1,3,6,6,1,Attchd,2,460,2,298,0,0,2007,8,4,181500
2,3,1,2001,3,1,2,6,6,1,Attchd,2,608,2,0,42,0,2008,8,4,223500
3,4,1,1915,3,1,2,7,6,1,Detchd,3,642,2,0,35,272,2006,8,0,140000
4,5,1,2000,4,1,2,9,6,1,Attchd,3,836,2,192,84,0,2008,8,4,250000

In [6]:
x=house.drop('GarageType',axis=1,inplace=True)

In [7]:
x=house.iloc[:,0:-1].values
x

array([[   1,    1, 2003, ..., 2008,    8,    4],
       [   2,    1, 1976, ..., 2007,    8,    4],
       [   3,    1, 2001, ..., 2008,    8,    4],
       ...,
       [1458,    1, 1941, ..., 2010,    8,    4],
       [1459,    1, 1950, ..., 2010,    8,    4],
       [1460,    1, 1965, ..., 2008,    8,    4]], dtype=int64)

In [8]:
y=house.iloc[:,-1].values
y

array([208500, 181500, 223500, ..., 266500, 142125, 147500], dtype=int64)

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [10]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [11]:
y_predict=lr.predict(x_test)
y_predict

array([152018.78832121, 170999.07977351, 148897.71468587, 217766.57487945,
       115754.59184851,  42495.27762826, 222640.7987493 , 173145.92966466,
       354775.7694951 , 153166.5729658 , 205823.3421545 , 137114.05088468,
       252271.77715408, 156123.93884377, 123565.98663602, 109224.17591066,
       249821.04164365,  88134.51561287, 143945.63419375, 163731.66634582,
       142901.99594672, 182376.11561638,  94844.36278761, 164475.88581619,
       221811.33272975, 171039.16994465, 155519.9057641 ,  54006.46382803,
       327890.6954896 , 122060.07450228, 170318.98032095, 230800.87313997,
       154809.78133091, 293306.51682808, 276986.48247264, 183236.81898625,
       270800.81416434, 126021.07888395, 258059.81145707, 298735.48918445,
       195388.62855659, 142769.27236527, 199174.23528447, 268236.40134126,
       332548.20105381, 142858.42531117, 132382.10049258, 125311.5214496 ,
       192470.68575328, 125115.83859986, 381863.18550324, 141456.09236901,
       183754.97041854,  79079.79305103, 192659.02889503, 132295.74904327,
       132357.94912504, 273645.71337414, 122587.77889432, 101015.56605579,
       150687.97660864, 114433.13235779, 155298.91641989, 168731.0062038 ,
       234026.82765394, 177505.30853228, 101069.10942606, 215169.687323  ,
       188766.7685317 , 218299.67342849, 204383.77293115,  92911.92553901,
       125908.47970423, 245428.78029876,  86922.3495601 , 253652.36684612,
       128724.36454601,  70930.08900584, 280049.94929   , 157029.46794037,
       132723.75988911, 127846.48649754,  49999.35287988, 147801.02507632,
       249800.25862213, 184068.52780835, 165774.26472803, 220959.84339864,
       186459.1660962 ,  97459.8382211 , 201348.20568709, 193428.08003736,
       186134.30997357, 227352.67607149, 239433.71583616, 150657.41065341,
       208493.10245551, 159199.51592899, 120647.1337458 , 167611.06228279,
       222104.7593497 , 233146.15452646, 157978.29668434, 152700.66700885,
       115309.03220182, 252090.92018187, 153880.12786575, 102761.69091698,
       238590.81862776, 116601.16665999, 109964.17350601, 100739.73366134,
       197486.56912004, 123606.81118595, 179543.88816678, 203517.89089195,
       340428.20362514, 107260.61469993, 213175.51600684, 298116.03639013,
       132744.66428046, 166329.71661225, 124935.11522108, 210794.06292481,
       186655.92589785, 241346.70933324, 321929.07029794, 219632.90425006,
       175607.30293957, 171482.46265326, 187139.66872201, 212335.30639165,
       197591.40333299, 208349.85422565,  87676.8996775 , 197252.14784347,
       158085.72930182, 168988.95833014,  83068.36657299, 198987.87596548,
       153420.26079092, 151079.58970857, 224327.36601926, 146104.68885354,
       116899.95923399, 203766.84688762, 219339.82046937, 120259.01545858,
       273418.42713807, 201072.42506697, 185601.59012242, 334791.20772739,
       287734.57918812,  66129.23828173, 168650.33663896, 315100.60089847,
       163253.83847063, 195645.65556164, 117983.54027714, 211401.95726112,
       116839.64157129, 127121.93068585, 196786.23444841, 164646.76045018,
       263042.17692869, 131005.46344748, 155872.05249318, 261652.69628868,
       219679.80964469, 186763.99484883, 197991.64590846, 186980.71925808,
       219408.69505702, 192573.22686592, 101553.4827692 , 104894.15215964,
       118076.50018792, 237997.28486277, 100767.57277759, 140977.98284082,
       199215.01565906, 216495.43451824, 121883.51904673, 250827.59624044,
       117494.3221204 , 195579.28864102, 110376.38360142, 211370.61527917,
       256494.00866827, 161779.82970397, 136233.20520854, 190778.17770053,
       201146.21231818, 150928.22932374, 105560.5641478 , 162748.83469029,
        79952.73938994, 123421.60325485, 191183.69236792, 137976.34041841,
        83126.0456328 , 195645.16767966, 148200.44241611,  79277.1069255 ,
        89039.73066245, 235150.20456611, 178936.85166652, 343878.45899103,
       259893.26500136,  53702.23372922, 193099.51716554, 237122.1343295 ,
        92826.34241653,  85894.20139248, 278205.77414287, 182267.04446648,
       175832.13812882, 243609.85789926, 239509.47400236,  59565.68220436,
       210277.86471508, 158318.11712205, 119094.09023954, 102418.80242179,
       212876.00133399, 290826.21046771, 234804.54783398, 185147.51195027,
       137241.1150876 , 160487.89668812,  94229.91347921, 165755.96098343,
        98673.86867515, 172864.96218806, 225358.5751469 , 119031.31689556,
        88430.16446315, 107698.89914622,  83354.80113523, 181626.30451734,
        97956.85460775, 200572.94544448, 229217.87035534, 211539.56150178,
       179181.71821641, 166449.62211665, 166578.42828835, 184566.25808389,
       158164.54291319, 193177.39472684, 241838.11304851, 304207.20979572,
        45214.78686341, 308867.85035613, 202826.95518784, 245046.88167027,
        79946.61080271, 261042.88860237, 393315.11398254, 498867.48844405,
       187772.07275294, 141328.3278192 , 128732.55174046,  58635.7920193 ,
       347708.96032661, 297776.64343751, 340368.02482967, 124512.47388945,
       138287.54175327, 235630.95482262, 116876.22015023, 217779.02936689,
       134546.2347808 , 191460.65826395,  85933.26391828, 220502.08231658,
       195108.27990574, 146390.03439788, 232409.06894642, 146949.37924369,
       128548.12892038, 318261.09606562, 179056.53715422, 128103.01903075,
       236985.33947705, 135499.51156701, 139823.3215328 , 241027.60103012,
       371649.19861039, 193068.21634389, 118038.56339278, 140208.77712137,
       294992.72821482, 107234.51478264, 104934.11945004, 282528.80055573,
       259884.02308283, 185424.08300379, 151668.39625102, 178312.18975931,
       124922.34718991, 143241.49783752, 226464.8156899 , 217756.12034615,
       181986.45757289, 143721.01241478, 163813.49317035, 202302.74510989,
       242798.18853436, 183847.27132358, 132556.11771972, 172591.43060795,
       145090.07757479, 116536.05967671, 144896.49431063, 161213.00844577,
       320480.964941  , 136163.9997134 , 210318.81669709, 171860.40517489,
        68430.3145313 , 243983.94979951, 131276.98321233, 277545.06610506,
       166091.8073088 , 243223.34539905, 150081.32495865, 332763.52050548,
       231884.79823356, 144056.19171166, 101586.67927796, 244963.65275622,
       138146.8688013 , 202954.76808246, 197289.36808417, 161995.55517439,
       173733.39120795, 225762.72713802, 149214.35373123, 117570.10183384,
       298872.91117622, 145623.01874681, 177428.65602526, 232435.62383197,
       182563.70932726, 134639.70043127, 131914.06839769, 123907.1273133 ,
        86166.46080478, 169353.27538984, 213621.96177137, 324797.77477938,
       106376.18502279,  89620.40663818, 166749.90053903, 330595.92369446,
       285564.85623253, 192278.08214876, 197969.96375078, 208362.3822493 ,
       265226.84622419, 191712.32293985, 193421.60602387, 253461.88863291,
        54561.59010126])

In [12]:
np.round(lr.score(x_test,y_test)*100)

68.0